######################################################################
# Automatically generated by qmake (2.01a) Thu May 16 08:02:14 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

#CONFIG += debug

# Input
SOURCES += \
CSudoku.cpp \
CQSudoku.cpp

HEADERS += \
CSudoku.h \
CQSudoku.h \

DESTDIR     = ../bin
OBJECTS_DIR = ../obj
LIB_DIR     = ../lib

INCLUDEPATH += \
../include \
.

unix:LIBS += \
-L$$LIB_DIR \
